name = "g18n_dev"
version = "1.3.0"

description = "Development tools and CLI for the g18n internationalization library"
licences = ["MIT"]
repository = { type = "github", user = "renatillas", repo = "g18n-dev" }
links = [{ title = "Website", href = "https://github.com/renatillas/g18n-dev" }]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
g18n = ">= 3.1.0"
argv = ">= 1.0.0 and < 2.0.0"
filepath = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.0.0 and < 3.0.0"
tom = ">= 1.0.0 and < 3.0.0"
shellout = ">= 1.7.0 and < 2.0.0"
snag = ">= 1.1.0 and < 2.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
trie_again = ">= 1.1.4 and < 2.0.0"
glance = "~> 5.0.1"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
